# Generated by Django 5.0.7 on 2024-08-13 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_categorie', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img_categorie', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_seller', models.BooleanField(default=False)),
                ('tendance', models.BooleanField(default=False)),
                ('vedette', models.BooleanField(default=False)),
                ('discount_produit', models.BooleanField(default=False)),
                ('img_produit', models.ImageField(blank=True, null=True, upload_to='grocery/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commande')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='dashboard.produit'),
        ),
    ]
