# Generated by Django 5.0.7 on 2024-08-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_produit',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='commande_produit',
            name='produits',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Commande_Produit',
        ),
    ]
