# Generated by Django 5.0.7 on 2024-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_categories_id_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_produit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
