# Generated by Django 5.0.7 on 2024-08-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_produit_id_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
